# Netlify configuration for Next.js (App Router) project located in frontend/
[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = "frontend/.next" # Plugin will adjust

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirect all to Next.js handler (plugin often injects, but explicit is safe)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/next"
  status = 200

