# Render infrastructure blueprint (optional)
# Apply via Render dashboard or `render.yaml` sync feature.
# Docs: https://render.com/docs/infrastructure-as-code

services:
  - type: web
    name: cf-hub-backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: ADDITIONAL_ORIGINS
        sync: false
      - key: API_BASE_PATH
        value: /api
      - key: FIREBASE_SERVICE_ACCOUNT_B64
        sync: false
      - key: R2_ACCOUNT_ID
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_BUCKET
        value: cf-hub-uploads
      - key: R2_PUBLIC_BASE_URL
        sync: false
      - key: MAX_UPLOAD_MB
        value: "8"
    healthCheckPath: /api/health

# Optional: Deploy frontend on Render instead of Netlify (uncomment to use)
#  - type: web
#    name: cf-hub-frontend
#    env: node
#    rootDir: frontend
#    plan: free
#    buildCommand: npm install && npm run build
#    startCommand: npm start
#    autoDeploy: true
#    envVars:
#      - key: NEXT_PUBLIC_API_URL
#        value: https://cf-hub-backend.onrender.com/api
#      - key: NEXT_PUBLIC_FIREBASE_API_KEY
#        sync: false
#      - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
#        sync: false
#      - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
#        sync: false
#      - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
#        sync: false
#      - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
#        sync: false
#      - key: NEXT_PUBLIC_FIREBASE_APP_ID
#        sync: false
#      - key: NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
#        sync: false
